package com.chandler.android.aca.kindredspirits;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class KindBook {

    //todo populate these arrays with more data

    public String[] mKindness = {
            "You matter.",
            "You are enough.",
            "Your smile lights up the room.",
           "I'm so glad you exist.",
            "What you're going through is temporary.",
            "You can survive this.",
            "I wish you all the best.",
            "You are working really hard and deserve success.",
            "You are a great friend.",
            "Your determination is amazing.",
            "Whatever you have been doing is working, keep it up.",
            "You are doing so great!",
            "You are making so much progress.",
            "You are the very best you.",
            "You are strong.",
            "You make a difference.",
            "You are important."
    };

    public String[] mKnope = {
            "You beautiful tropical fish.",
            "You’re smart as a whip and you’re cool under pressure.",
            "You’re a beautiful, talented, brilliant, powerful musk-ox.",
            "You are such a good friend.",
            "You cunning, pliable, chestnut-haired sunfish",
            "You’re a genius! Your brain is almost as perfect as your face",
            "You beautiful, naïve, sophisticated newborn baby.",
            "You poetic, noble land-mermaid.",
            "You beautiful, rule-breaking moth.",
            "You beautiful, devious bastard.",
            "You beautiful spinster. I will find you love.",
            "You wild, majestic unicorn.",
            "You’re so sweet and innocent and pretty.",
            "I always forget because you're so pretty, you're not used to rejection.",
            "You are so brilliant and kind and stupid hot, you’re definitely " +
                    "going to find a wonderful person who loves you and respects you " +
                    "and fills your home with beautiful genius babies.",
            "You’re so beautiful. I mean, you’re always beautiful, " +
                    "but right now you’re the most beautiful, glowing, sun goddess ever.",
            "You spectacular, golden-tongued sunflower.",
            "You are the greatest human being ever invented.",
            "There is nothing harder in the entire world than saying no to your beautiful face.",
            "You tricky minx.",
            "Now I have two best friends: you and you. Each one more beautiful than the other.",
            "You're beautiful and you're organized!",
            "No one can fill your shoes, with your perfect little doll feet.",
            "You beautiful, coy bastard.",
            "You are the smartest, most accomplished person I know. And check out that bod!",
            "You barrell of monkeys...and kindness.",
            "You beautiful, confused defender of justice.",
            "You magnificent tree of life.",
            "You delicious stack of waffles.",
            "You equine, L'il Sebastian-spirited ballerina.",
            "You sly industrial park.",
            "You impish, beautiful liger.",
            "You spectacular cloud of brilliance.",
            "You compassionate ranger of parks.",
            "You unstoppable, glamorous freight train.",
            "You gorgeous, simple house cat.",
            "You fluorescent light bulb of truth.",
            "You handsome, genius child.",
            "You clever, wonderful flying squirrel.",
            "You wild and crazy flower pot.",
            "You elegant, tiny bus driver.",
            "You beautiful, misunderstood sports car.",
            "You vivacious rainbow of joy.",
            "You adorable, miniature horse.",
            "You gorgeous, purebred poodle.",
            "You transcendent, little seahorse",
            "You sneaky, persistent ice sculptor.",
            "You elusive, runaway hot air balloon.",
            "You humble, intelligent golden retriever.",
            "You phenomenal well of ideas.",
            "You magnificent middle school marching band.",
            "You priceless, expensive gem.",
            "You flawless, apple pie."
    };

    public String[] mReality = {
            "Be the change you wish to see in the world. \n-Mahatma Gandhi",
            "I dream, therefore I become. \n-Cheryl Grossman",
            "Life is too short for traffic. \n-Dan Bellack",
            "A stumble may prevent a fall. \n-English proverb",
            "Every path serves a purpose. \n-Gene Oliver",
            "What worries you, masters you. \n-Haddon W. Robinson",
            "Life is a continual upgrade. \n-J. Mark Wallace",
            "Not all who wander are lost. \n-J. R. R. Tolkien",
            "Focus on remedies, not faults. \n-Jack Nicklaus",
            "Never cut what you can untie. \n-Jeseph Joubert",
            "Blind belief is dangerous. \n-Kenyan Proverb",
            "If there is no wind, row. \n-Latin proverb",
            "When in doubt, tell the truth. \n-Mark Twain",
            "Courage conquers all things. \n-Ovid",
            "Lead, follow, or get out of the way. \n-Thomas Paine",
            "Courage doesn't always roar. \n-Mary Anne Radmacher",
            "Another Sunrise, another New Beginning. \n-Jonathan Lockwood Huie",
            "Believe in yourself.  \n-Anonymous",
            "It's never too late.  \n-Anonymous",
            "Be Here Now.  \n-Ram Dass",
            "Follow Your Dreams.  \n-Anonymous",
            "This too, shall pass.  \n-Bible",
            "Live Your Dreams.  \n-Les Brown",
            "Believe that life is worth living and your belief will help create the fact.  \n-William James",
            "Live life to the fullest.  \n-Robert Louis Stevenson",
            "Life's burdens are lighter when I laugh at myself.  \n-Jonathan Lockwood Huie",
            "Life is really simple, but we insist on making it complicated.  \n-Confucius",
            "Choose your Habits, Choose your Life.  \n-Jonathan Lockwood Huie",
            "Life is what happens while you are busy making other plans.  \n-John Lennon",
            "Gather strength from life's storms.  \n-Jonathan Lockwood Huie",
            "Follow your own star.  \n-Anonymous",
            "Joy is a Choice - but Not an Easy Choice.  \n-Jonathan Lockwood Huie",
            "Anything Is Possible.  \n-Anonymous",
            "Happiness depends upon ourselves.  \n-Aristotle",
            "Nothing great was ever achieved without enthusiasm.  \n-Ralph Waldo Emerson",
            "Know thyself.  \n-Socrates",
            "Attitude is everything.  \n-Anonymous",
            "Count Your Blessings.  \n-Og Mandino",
            "He is richest who is content with the least.  \n-Socrates",
            "Everything has beauty, but not everyone sees it.  \n-Confucius",
            "Reach for the stars.  \n-Anonymous",
            "Choose the World You See.  \n-Jonathan Lockwood Huie",
            "Gifts freely given are never obligations.  \n-Jonathan Lockwood Huie",
            "Today is the tomorrow you worried about yesterday.  \n-Anonymous",
            "Life is too important to be taken seriously.  \n-Oscar Wilde",
            "Learn the rules so you know how to break them properly.  \n-Dalai Lama",
            "Humor is reason gone mad.  \n-Groucho Marx",
            "Minds are like parachutes. They only function when they are open.  \n-James Dewar",
            "A man can't be too careful in the choice of his enemies.  \n-Oscar Wilde",
            "A remark generally hurts in proportion to its truth.  \n-Will Rogers",
            "I can resist everything except temptation.  \n-Oscar Wilde",
            "A true friend stabs you in the front.  \n-Oscar Wilde",
            "The light at the end of the tunnel may be an oncoming train.  \n-Anonymous",
            "Don't dream it, be it.  \n-Rocky Horror Picture Show",
            "Celebrate endings - for they precede new beginnings.  \n-Jonathan Lockwood Huie",
            "To change who you are, change who you think you are.   \n-Jonathan Lockwood Huie",
            "Be Here Now.  \n-Ram Dass",
            "Stay Alert, and doors will open.  \n-Jonathan Lockwood Huie",
            "Choose the World You See, and See the World You Choose.  \n-Jonathan Lockwood Huie",
            "Courage is the power to let go of the familiar.  \n-Raymond Lindquist",
            "Thinking will not overcome fear but action will.  \n-W. Clement Stone",
            "No one knows what he can do until he tries.  \n-Publilius Syrus",
            "Today is the first day of the rest of your life.  \n-Anonymous",
            "The starting point of all achievement is desire.  \n-Napoleon Hill",
            "The man who is successful is the man who is useful.  \n-Bourke Cockran",
            "Success is getting what you want; happiness is wanting what you get.  \n-Dale Carnegie",
            "Self-trust is the first secret of success.  \n-Ralph Waldo Emerson",
            "In order to succeed, you must first be willing to fail.  \n-Anonymous",
            "Failure is success if we learn from it.  \n-Malcolm Forbes",
            "Success consists of going from failure to failure without loss of enthusiasm.  \n-Winston Churchill",
            "Never let the fear of striking out get in your way.  \n-Babe Ruth",
            "Winning isn't everything, but wanting to win is.  \n-Vince Lombardi",
            "Confidence is contagious. So is lack of confidence.  \n-Vince Lombardi",
            "It's what you learn after you know it all that counts.  \n-John Wooden",
            "Don't let what you cannot do interfere with what you can do.  \n-John Wooden",
            "Every wall is a door.  \n-Ralph Waldo Emerson",
            "Fall seven times, stand up eight.  \n-Japanese Proverb",
            "Where there's a will, there's a way.  \n-Old English proverb",
            "Don’t wait. The time will never be just right.  \n-Napoleon Hill",
            "Remember no one can make you feel inferior without your consent.  \n-Eleanor Roosevelt",
            "Do what you can, with what you have, where you are.  \n-Theodore Roosevelt",
            "You must do the thing you think you cannot do.  \n-Eleanor Roosevelt",
            "Don’t regret the past, just learn from it.  \n-Ben Ipock",
            "It does not matter how slowly you go as long as you do not stop.  \n-Confucius",
            "It is never too late to be what you might have been.  \n-Anonymous",
            "An obstacle is often a stepping stone.  \n-Prescott Bush",
            "Dream big and dare to fail.  \n-Norman Vaughan",
            "The secret to getting ahead is getting started.  \n-Mark Twain",
            "Act as if what you do makes a difference. It does.  \n-William James",
            "You have enemies? Good. That means you’ve stood up for something, sometime in your life.  \n-Winston Churchill",
            "What you do today can improve all your tomorrows.  \n-Ralph Marston",
            "Every strike brings me closer to the next home run.  \n-Babe Ruth",
            "The World is what we think it is. If we can change our thoughts, we can change the world.  \n-H.M. Tomlinson",
            "No pessimist ever discovered the secrets of the stars, or sailed to an uncharted land, or opened a new heaven to the human spirit.  \n-Helen Keller",
            "Life isn’t about finding yourself. Life’s about creating yourself.  \n-George Bernard Shaw",
            "If you don’t like something change it; if you can’t change it, change the way you think about it. \n-Unknown",
            "You must begin to think of yourself as becoming the person you want to be.  \n-David Viscott",
            "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.  \n-Norman Vincent Peale",
            "What ever the mind of man can conceive and believe, it can achieve.  \n-Napolean Hill",
    };

    public String[] mAffirmations = {
            "I am kind.",
            "I am smart.",
            "I am important.",
            "I am the architect of my life; I build its foundation and choose its contents.",
            "Today, I have energy and joy.",
            "My body is healthy; my mind is brilliant; my soul is tranquil.",
            "I am superior to negative thoughts and low actions.",
            "I have endless talents which I begin to utilize today.",
            "I forgive those who have harmed me in my past and peacefully detach from them.",
            "A river of compassion washes away my anger and replaces it with love.",
            "I possess the qualities needed to be extremely successful.",
            "My success is growing, expanding, and thriving.",
            "Creative energy surges through me and leads me to new and brilliant ideas.",
            "Happiness is a choice. I base my happiness on my own accomplishments and the blessings I’ve been given.",
            "My ability to conquer my challenges is limitless; my potential to succeed is infinite.",
            "I deserve to be employed and paid well for my time, efforts, and ideas. Each day, I am closer to finding the perfect job for me.",
            "I am courageous and I stand up for myself.",
            "My thoughts are filled with positivity and my life is plentiful with prosperity.",
            "Today, I abandon my old habits and take up new, more positive ones.",
            "Many people look up to me and recognize my worth; I am admired.",
            "I acknowledge my own self-worth; my confidence is soaring.",
            "I am a powerhouse; I am indestructible.",
            "Though these times are difficult, they are only a short phase of life.",
            "My future is an ideal projection of what I envision now.",
            "My efforts are being supported by the universe; my dreams manifest into reality before my eyes.",
            "I radiate beauty, charm, and grace.",
            "My obstacles are moving out of my way; my path is carved towards greatness.",
            "I begin each day with strength in my heart and clarity in my mind.",
            "My fears of tomorrow are simply melting away.",
            "I am at peace with all that has happened, is happening, and will happen.",
            "My life is just beginning.",
            "Happiness is my birthright. I embrace happiness as my set point state of being.",
            "I feel joy and contentment in this moment right now.",
            "I awaken in the morning feeling happy and enthusiastic about life.",
            "I can tap into a wellspring of inner happiness anytime I wish.",
            "By allowing myself to be happy, I inspire others to be happy as well.",
            "I have fun with all of my endeavors, even the most mundane.",
            "I look at the world around me and can’t help but smile and feel joy.",
            "I find joy and pleasure in the most simple things in life.",
            "I have an active sense of humor and love to share laughter with others.",
            "My heart is overflowing with joy.",
            "I rest in happiness when I go to sleep, knowing all is well in my world.",
            "I expect to be successful in all of my endeavors. Success is my natural state.",
            "I easily find solutions to challenges and roadblocks and move past them quickly.",
            "Mistakes and setbacks are stepping stones to my success because I learn from them.",
            "Every day in every way, I am becoming more and more successful.",
            "I feel successful with my life right now, even as I work toward future success.",
            "I know exactly what I need to do to achieve success.",
            "I see fear as the fuel for my success and take bold action in spite of fear.",
            "I feel powerful, capable, confident, energetic, and on top of the world.",
            "I have an intention for success and know it is a reality awaiting my arrival.",
            "I am reaching my goals and feel the excitement of my achievement.",
            "Today I am successful. Tomorrow I will be successful. Every day I am successful.",
            "When I breath, I inhale confidence and exhale my doubts.",
            "I love meeting strangers and approach them with boldness and enthusiasm.",
            "I live in the present and am confident of the future.",
            "My personality exudes confidence. I am bold and outgoing.",
            "I am self-reliant, creative and persistent in whatever I do.",
            "I am energetic and enthusiastic. Confidence is my second nature.",
            "I always attract only the best of circumstances and the best positive people in my life.",
            "I am a problem solver. I focus on solutions and always find the best solution.",
            "I accept change and easily adjust myself to new situations.",
            "Self confidence is what I thrive on. Nothing is impossible and life is great.",
            "I see only the good in others. I attract only positive confident people.",
            "I approve of myself and love myself deeply and completely.",
            "I am unique. I feel good about being alive and being me.",
            "I trust myself and know my inner wisdom is my best guide.",
            "I have integrity. I am totally reliable. I do what I say.",
            "I act from a place of personal security.",
            "I fully accept myself and know that I am worthy of great things in life.",
            "I choose to be proud of myself.",
            "I find deep inner peace within myself as I am.",
            "I fill my mind with positive and nourishing thoughts.",
            "My confidence, self esteem, and inner wisdom are increasing with each day.",
            "Every cell of my being vibrates with energy and health.",
            "I am rested, and my body is full of energy.",
            "I nourish my body with healthy food.",
            "All of my body systems are functioning perfectly.",
            "My body is healing, and I feel better and better every day.",
            "I enjoy exercising my body and strengthening my muscles.",
            "With every breath out, I release stress in my body.",
            "I send love and healing to every organ of my body.",
            "I breathe deeply, exercise regularly and feed only good nutritious food to my body.",
            "I pay attention and listen to what my body needs for health and vitality.",
            "I sleep soundly and peacefully, and awaken feeling rested and energetic.",
            "I am surrounded by people who encourage and support healthy choices.",
            "My world is a peaceful, loving, and joy-filled place to live.",
            "I sow the seeds of peace wherever I go.",
            "I surround myself with peaceful people.",
            "My work environment is calm and peaceful.",
            "I breath in peace, I breath out chaos and disorder.",
            "My home is a peaceful sanctuary where I feel safe and happy.",
            "In all that I say and do, I choose peace.",
            "I release past anger and hurts and fill myself with serenity and peaceful thoughts.",
            "Peace descends all around me now and always.",
            "I send peace from myself into the world.",
            "I respond peacefully in all situations.",
            "I am grounded in the experience of the present moment.",
            "I am focus and engaged in the task at hand.",
            "All is well right now.",
            "I am grateful for this moment and find joy in it.",
            "I gently and easily return to the present moment.",
            "I observe my thoughts and actions without judging them.",
            "I am fully present in all of my relationships.",
            "Life is happening in this moment.",
            "I accept and embrace all experiences, even unpleasant ones.",
            "I meditate easily without resistance or anxiety.",
            "I release the past and live fully in the present moment.",
            "Calmness washes over me with every deep breath I take.",
            "Every day I am more and more at ease.",
            "Being calm and relaxed energizes my whole being.",
            "All the muscles in my body are releasing and relaxing.",
            "All negativity and stress are evaporating from my body and my mind.",
            "I breath in relaxation. I breath out stress.",
            "Even when there is chaos around me, I remain calm and centered.",
            "I transcend stress of any kind. I live in peace.",
            "I am free of anxiety, and a calm inner peace fills my mind and body.",
            "All is well in my world. I am calm, happy, and content.",
            "When I believe in myself, so do others.",
            "I express my needs and feelings.",
            "I am my own unique self - special, creative and wonderful.",
            "I allow my life to be prosperous.",
            "I rejoice in the abundance around me.",
            "I am grateful for what I already have.",
            "I easily create abundance in my life.",
            "The Universe is overflowing with abundance.",
            "I receive the Universal flow of abundance.",
            "I acknowledge my abundant good health.",
            "I acknowledge my prosperous outlook on life.",
            "I release any anxiety I am holding onto.",
            "My current state of being is peaceful.",
            "I am calm.",
            "Each and every day, my circumstances are improving.",
            "I am consciously aware of the calm silence of my inner spirit.",
            "My awareness is anchored in tranquility.",
            "I am stable during life’s ups and downs.",
            "I am willing to let my anxious thoughts go. Each day I embrace a positive attitude.",
            "From head to toe, I am relaxed.",
            "I am centered.",
            "The best way out is through.",
            "I allow my thoughts to be what they are. I let go of the urge to dictate my life’s direction.",
            "I am open to whatever the outcome may be.",
            "I trust that there is purpose behind my challenges.",
            "I accept myself, and my loved ones, just as we are.",
            "I choose to focus on what I can control and trust that the rest will work out.",
            "I already have the experience and understanding I need to perform my absolute best.",
            "I know that I have the knowledge and resources to achieve my dreams.",
            "I act from a place of personal security.",
            "I fully accept myself and know that I am worthy of great things in life.",
            "I choose act with poise and grace.",
            "I choose to be proud of myself.",
            "I am willing to learn from my successes and challenges to get better each day.",
            "I have deep connections with my friends.",
            "My friendships are filled with love and joy.",
            "I am thankful for my friends.",
            "I harmoniously resolve conflicts with my friend for the highest good within each of us.",
            "My friends are a source of happiness in my life.",
            "I surrounded by the love of friends.",
            "My friends are my family.",
            "I feel safe and comforted by my friends.",
            "I welcome freedom into my mind.",
            "I release all fear from my life.",
            "I am safe.",
            "I am free to live in peace and security.",
            "I am willing to let fear go and live in harmony with all life.",
            "Fear is just a thought. It is not based in reality, and it does not control my actions.",
            "I am free from fearful thoughts.",
            "My inner spirit is grounded in peace and it expands to embrace my thoughts.",
            "My thoughts are filled with peace and tranquility.",
            "I laugh until I cry in the presence of friends.",
            "My friends allow me the freedom to be who I truly am.",
    };


    public String getKindness(){
        String kindness;
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mKindness.length);
        kindness = mKindness[randomNumber];

        return kindness;
    }


    public String getKnope(){
        String knope;
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mKnope.length);
        knope = mKnope[randomNumber];

        return knope;
    }

    public String getRealityCheck(){
        String realityCheck;
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mAffirmations.length);
        realityCheck = mAffirmations[randomNumber];

        return realityCheck;
    }

    public String getReality(){
        String quote;
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mReality.length);
        quote = mReality[randomNumber];

        return quote;
    }

    public String[] getArrays(){
        String[] chosen;
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mArrayList.size());
        chosen = mArrayList.get(randomNumber);

        return chosen;
    }

    public List<String[]> mArrayList = new ArrayList<>();

   /* mReality,
    mKnope,
    mKindness,
    mAffirmations*/

}
